// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from "@prisma/orm-postgres/adapter/operation-types";
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from "@prisma/orm-postgres/target/codec-types";

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from "@prisma/orm-postgres/family-contract/types";
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from "@prisma/orm-postgres/contract/types";

export type StorageHash =
  StorageHashBase<"efeb0c702c79c7f566c83bbdf282495207ff419369dfe32cf360041d2153d036">;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<"3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2">;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly "pg/float@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/float4@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/float8@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/int@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/int2@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/int4@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/int8@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/interval@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/numeric@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/time-string@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/time-temporal@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "sql/float@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly "pg/int@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/int2@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/int4@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/int8@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/numeric@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: {
      readonly output: "pg/int8number@1";
      readonly nullable: false;
    };
    readonly anyInput: {
      readonly output: "pg/int8number@1";
      readonly nullable: false;
    };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: {
      readonly output: "pg/int8@1";
      readonly nullable: false;
    };
    readonly anyInput: {
      readonly output: "pg/int8@1";
      readonly nullable: false;
    };
  };
  readonly max: {
    readonly byCodec: {
      readonly "pg/char@1": {
        readonly output: "pg/char@1";
        readonly nullable: true;
      };
      readonly "pg/date-string@1": {
        readonly output: "pg/date-string@1";
        readonly nullable: true;
      };
      readonly "pg/date-temporal@1": {
        readonly output: "pg/date-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/enum@1": {
        readonly output: "pg/enum@1";
        readonly nullable: true;
      };
      readonly "pg/float@1": {
        readonly output: "pg/float@1";
        readonly nullable: true;
      };
      readonly "pg/float4@1": {
        readonly output: "pg/float4@1";
        readonly nullable: true;
      };
      readonly "pg/float8@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/inet@1": {
        readonly output: "pg/inet@1";
        readonly nullable: true;
      };
      readonly "pg/int@1": {
        readonly output: "pg/int@1";
        readonly nullable: true;
      };
      readonly "pg/int2@1": {
        readonly output: "pg/int2@1";
        readonly nullable: true;
      };
      readonly "pg/int4@1": {
        readonly output: "pg/int4@1";
        readonly nullable: true;
      };
      readonly "pg/int8@1": {
        readonly output: "pg/int8@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/interval@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/numeric@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/text@1": {
        readonly output: "pg/text@1";
        readonly nullable: true;
      };
      readonly "pg/text-array@1": {
        readonly output: "pg/text-array@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-string@1": {
        readonly output: "pg/timestamp-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-temporal@1": {
        readonly output: "pg/timestamp-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-string@1": {
        readonly output: "pg/timestamptz-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-temporal@1": {
        readonly output: "pg/timestamptz-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/time-string@1": {
        readonly output: "pg/time-string@1";
        readonly nullable: true;
      };
      readonly "pg/time-temporal@1": {
        readonly output: "pg/time-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timetz@1": {
        readonly output: "pg/timetz@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "pg/varchar@1": {
        readonly output: "pg/text@1";
        readonly nullable: true;
      };
      readonly "sql/char@1": {
        readonly output: "sql/char@1";
        readonly nullable: true;
      };
      readonly "sql/float@1": {
        readonly output: "sql/float@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": {
        readonly output: "sql/int@1";
        readonly nullable: true;
      };
      readonly "sql/text@1": {
        readonly output: "sql/text@1";
        readonly nullable: true;
      };
      readonly "sql/varchar@1": {
        readonly output: "pg/text@1";
        readonly nullable: true;
      };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly "pg/char@1": {
        readonly output: "pg/char@1";
        readonly nullable: true;
      };
      readonly "pg/date-string@1": {
        readonly output: "pg/date-string@1";
        readonly nullable: true;
      };
      readonly "pg/date-temporal@1": {
        readonly output: "pg/date-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/enum@1": {
        readonly output: "pg/enum@1";
        readonly nullable: true;
      };
      readonly "pg/float@1": {
        readonly output: "pg/float@1";
        readonly nullable: true;
      };
      readonly "pg/float4@1": {
        readonly output: "pg/float4@1";
        readonly nullable: true;
      };
      readonly "pg/float8@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/inet@1": {
        readonly output: "pg/inet@1";
        readonly nullable: true;
      };
      readonly "pg/int@1": {
        readonly output: "pg/int@1";
        readonly nullable: true;
      };
      readonly "pg/int2@1": {
        readonly output: "pg/int2@1";
        readonly nullable: true;
      };
      readonly "pg/int4@1": {
        readonly output: "pg/int4@1";
        readonly nullable: true;
      };
      readonly "pg/int8@1": {
        readonly output: "pg/int8@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/interval@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/numeric@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/text@1": {
        readonly output: "pg/text@1";
        readonly nullable: true;
      };
      readonly "pg/text-array@1": {
        readonly output: "pg/text-array@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-string@1": {
        readonly output: "pg/timestamp-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-temporal@1": {
        readonly output: "pg/timestamp-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-string@1": {
        readonly output: "pg/timestamptz-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-temporal@1": {
        readonly output: "pg/timestamptz-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/time-string@1": {
        readonly output: "pg/time-string@1";
        readonly nullable: true;
      };
      readonly "pg/time-temporal@1": {
        readonly output: "pg/time-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timetz@1": {
        readonly output: "pg/timetz@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "pg/varchar@1": {
        readonly output: "pg/text@1";
        readonly nullable: true;
      };
      readonly "sql/char@1": {
        readonly output: "sql/char@1";
        readonly nullable: true;
      };
      readonly "sql/float@1": {
        readonly output: "sql/float@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": {
        readonly output: "sql/int@1";
        readonly nullable: true;
      };
      readonly "sql/text@1": {
        readonly output: "sql/text@1";
        readonly nullable: true;
      };
      readonly "sql/varchar@1": {
        readonly output: "pg/text@1";
        readonly nullable: true;
      };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly "pg/float@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/float4@1": {
        readonly output: "pg/float4@1";
        readonly nullable: true;
      };
      readonly "pg/float8@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/int@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/int2@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/int4@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/int8@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/interval@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/numeric@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/time-string@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/time-temporal@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "sql/float@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly "pg/int@1": {
        readonly output: "pg/int8@1";
        readonly nullable: true;
      };
      readonly "pg/int2@1": {
        readonly output: "pg/int8@1";
        readonly nullable: true;
      };
      readonly "pg/int4@1": {
        readonly output: "pg/int8@1";
        readonly nullable: true;
      };
      readonly "pg/int8@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": {
        readonly output: "pg/int8@1";
        readonly nullable: true;
      };
    };
  };
};
type DefaultLiteralValue<
  CodecId extends string,
  Encoded,
> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]["json"]
    ? Encoded
    : CodecTypes[CodecId]["json"]
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Booking: {
      readonly id: CodecTypes["pg/int4@1"]["output"];
      readonly userId: CodecTypes["pg/int4@1"]["output"];
      readonly destinationId: CodecTypes["pg/int4@1"]["output"];
      readonly bookingDate: CodecTypes["pg/timestamptz-temporal@1"]["output"];
      readonly status: CodecTypes["pg/text@1"]["output"];
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
    };
    readonly Destination: {
      readonly id: CodecTypes["pg/int4@1"]["output"];
      readonly name: CodecTypes["pg/text@1"]["output"];
      readonly province: CodecTypes["pg/text@1"]["output"];
      readonly region: CodecTypes["pg/text@1"]["output"];
      readonly category: CodecTypes["pg/text@1"]["output"];
      readonly description: CodecTypes["pg/text@1"]["output"];
      readonly image: CodecTypes["pg/text@1"]["output"];
      readonly bestFor: CodecTypes["pg/text@1"]["output"] | null;
      readonly mapsUrl: CodecTypes["pg/text@1"]["output"] | null;
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
    };
    readonly Food: {
      readonly id: CodecTypes["pg/int4@1"]["output"];
      readonly name: CodecTypes["pg/text@1"]["output"];
      readonly description: CodecTypes["pg/text@1"]["output"];
      readonly image: CodecTypes["pg/text@1"]["output"];
      readonly category: CodecTypes["pg/text@1"]["output"];
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
    };
    readonly Review: {
      readonly id: CodecTypes["pg/int4@1"]["output"];
      readonly userId: CodecTypes["pg/int4@1"]["output"];
      readonly destinationId: CodecTypes["pg/int4@1"]["output"];
      readonly rating: CodecTypes["pg/int4@1"]["output"];
      readonly comment: CodecTypes["pg/text@1"]["output"];
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
    };
    readonly Tip: {
      readonly id: CodecTypes["pg/int4@1"]["output"];
      readonly title: CodecTypes["pg/text@1"]["output"];
      readonly description: CodecTypes["pg/text@1"]["output"];
      readonly category: CodecTypes["pg/text@1"]["output"];
      readonly image: CodecTypes["pg/text@1"]["output"] | null;
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
    };
    readonly User: {
      readonly id: CodecTypes["pg/int4@1"]["output"];
      readonly name: CodecTypes["pg/text@1"]["output"];
      readonly email: CodecTypes["pg/text@1"]["output"];
      readonly password: CodecTypes["pg/text@1"]["output"];
      readonly role: CodecTypes["pg/text@1"]["output"];
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Booking: {
      readonly id: CodecTypes["pg/int4@1"]["input"];
      readonly userId: CodecTypes["pg/int4@1"]["input"];
      readonly destinationId: CodecTypes["pg/int4@1"]["input"];
      readonly bookingDate: CodecTypes["pg/timestamptz-temporal@1"]["input"];
      readonly status: CodecTypes["pg/text@1"]["input"];
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
    };
    readonly Destination: {
      readonly id: CodecTypes["pg/int4@1"]["input"];
      readonly name: CodecTypes["pg/text@1"]["input"];
      readonly province: CodecTypes["pg/text@1"]["input"];
      readonly region: CodecTypes["pg/text@1"]["input"];
      readonly category: CodecTypes["pg/text@1"]["input"];
      readonly description: CodecTypes["pg/text@1"]["input"];
      readonly image: CodecTypes["pg/text@1"]["input"];
      readonly bestFor: CodecTypes["pg/text@1"]["input"] | null;
      readonly mapsUrl: CodecTypes["pg/text@1"]["input"] | null;
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
    };
    readonly Food: {
      readonly id: CodecTypes["pg/int4@1"]["input"];
      readonly name: CodecTypes["pg/text@1"]["input"];
      readonly description: CodecTypes["pg/text@1"]["input"];
      readonly image: CodecTypes["pg/text@1"]["input"];
      readonly category: CodecTypes["pg/text@1"]["input"];
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
    };
    readonly Review: {
      readonly id: CodecTypes["pg/int4@1"]["input"];
      readonly userId: CodecTypes["pg/int4@1"]["input"];
      readonly destinationId: CodecTypes["pg/int4@1"]["input"];
      readonly rating: CodecTypes["pg/int4@1"]["input"];
      readonly comment: CodecTypes["pg/text@1"]["input"];
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
    };
    readonly Tip: {
      readonly id: CodecTypes["pg/int4@1"]["input"];
      readonly title: CodecTypes["pg/text@1"]["input"];
      readonly description: CodecTypes["pg/text@1"]["input"];
      readonly category: CodecTypes["pg/text@1"]["input"];
      readonly image: CodecTypes["pg/text@1"]["input"] | null;
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
    };
    readonly User: {
      readonly id: CodecTypes["pg/int4@1"]["input"];
      readonly name: CodecTypes["pg/text@1"]["input"];
      readonly email: CodecTypes["pg/text@1"]["input"];
      readonly password: CodecTypes["pg/text@1"]["input"];
      readonly role: CodecTypes["pg/text@1"]["input"];
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly booking: {
      readonly bookingDate: CodecTypes["pg/timestamptz-temporal@1"]["output"];
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
      readonly destinationId: CodecTypes["pg/int4@1"]["output"];
      readonly id: CodecTypes["pg/int4@1"]["output"];
      readonly status: CodecTypes["pg/text@1"]["output"];
      readonly userId: CodecTypes["pg/int4@1"]["output"];
    };
    readonly destination: {
      readonly bestFor: CodecTypes["pg/text@1"]["output"] | null;
      readonly category: CodecTypes["pg/text@1"]["output"];
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
      readonly description: CodecTypes["pg/text@1"]["output"];
      readonly id: CodecTypes["pg/int4@1"]["output"];
      readonly image: CodecTypes["pg/text@1"]["output"];
      readonly mapsUrl: CodecTypes["pg/text@1"]["output"] | null;
      readonly name: CodecTypes["pg/text@1"]["output"];
      readonly province: CodecTypes["pg/text@1"]["output"];
      readonly region: CodecTypes["pg/text@1"]["output"];
    };
    readonly food: {
      readonly category: CodecTypes["pg/text@1"]["output"];
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
      readonly description: CodecTypes["pg/text@1"]["output"];
      readonly id: CodecTypes["pg/int4@1"]["output"];
      readonly image: CodecTypes["pg/text@1"]["output"];
      readonly name: CodecTypes["pg/text@1"]["output"];
    };
    readonly review: {
      readonly comment: CodecTypes["pg/text@1"]["output"];
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
      readonly destinationId: CodecTypes["pg/int4@1"]["output"];
      readonly id: CodecTypes["pg/int4@1"]["output"];
      readonly rating: CodecTypes["pg/int4@1"]["output"];
      readonly userId: CodecTypes["pg/int4@1"]["output"];
    };
    readonly tip: {
      readonly category: CodecTypes["pg/text@1"]["output"];
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
      readonly description: CodecTypes["pg/text@1"]["output"];
      readonly id: CodecTypes["pg/int4@1"]["output"];
      readonly image: CodecTypes["pg/text@1"]["output"] | null;
      readonly title: CodecTypes["pg/text@1"]["output"];
    };
    readonly user: {
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
      readonly email: CodecTypes["pg/text@1"]["output"];
      readonly id: CodecTypes["pg/int4@1"]["output"];
      readonly name: CodecTypes["pg/text@1"]["output"];
      readonly password: CodecTypes["pg/text@1"]["output"];
      readonly role: CodecTypes["pg/text@1"]["output"];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly booking: {
      readonly bookingDate: CodecTypes["pg/timestamptz-temporal@1"]["input"];
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
      readonly destinationId: CodecTypes["pg/int4@1"]["input"];
      readonly id: CodecTypes["pg/int4@1"]["input"];
      readonly status: CodecTypes["pg/text@1"]["input"];
      readonly userId: CodecTypes["pg/int4@1"]["input"];
    };
    readonly destination: {
      readonly bestFor: CodecTypes["pg/text@1"]["input"] | null;
      readonly category: CodecTypes["pg/text@1"]["input"];
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
      readonly description: CodecTypes["pg/text@1"]["input"];
      readonly id: CodecTypes["pg/int4@1"]["input"];
      readonly image: CodecTypes["pg/text@1"]["input"];
      readonly mapsUrl: CodecTypes["pg/text@1"]["input"] | null;
      readonly name: CodecTypes["pg/text@1"]["input"];
      readonly province: CodecTypes["pg/text@1"]["input"];
      readonly region: CodecTypes["pg/text@1"]["input"];
    };
    readonly food: {
      readonly category: CodecTypes["pg/text@1"]["input"];
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
      readonly description: CodecTypes["pg/text@1"]["input"];
      readonly id: CodecTypes["pg/int4@1"]["input"];
      readonly image: CodecTypes["pg/text@1"]["input"];
      readonly name: CodecTypes["pg/text@1"]["input"];
    };
    readonly review: {
      readonly comment: CodecTypes["pg/text@1"]["input"];
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
      readonly destinationId: CodecTypes["pg/int4@1"]["input"];
      readonly id: CodecTypes["pg/int4@1"]["input"];
      readonly rating: CodecTypes["pg/int4@1"]["input"];
      readonly userId: CodecTypes["pg/int4@1"]["input"];
    };
    readonly tip: {
      readonly category: CodecTypes["pg/text@1"]["input"];
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
      readonly description: CodecTypes["pg/text@1"]["input"];
      readonly id: CodecTypes["pg/int4@1"]["input"];
      readonly image: CodecTypes["pg/text@1"]["input"] | null;
      readonly title: CodecTypes["pg/text@1"]["input"];
    };
    readonly user: {
      readonly createdAt: CodecTypes["pg/timestamptz-temporal@1"]["input"];
      readonly email: CodecTypes["pg/text@1"]["input"];
      readonly id: CodecTypes["pg/int4@1"]["input"];
      readonly name: CodecTypes["pg/text@1"]["input"];
      readonly password: CodecTypes["pg/text@1"]["input"];
      readonly role: CodecTypes["pg/text@1"]["input"];
    };
  };
};

export namespace Models {
  export type public_User = {
    id: CodecTypes["pg/int4@1"]["output"];
    name: CodecTypes["pg/text@1"]["output"];
    email: CodecTypes["pg/text@1"]["output"];
    password: CodecTypes["pg/text@1"]["output"];
    role: CodecTypes["pg/text@1"]["output"];
    createdAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
    bookings: public_Booking[];
    reviews: public_Review[];
    readonly [RelationKeys]?: "bookings" | "reviews";
  };
  export type public_Destination = {
    id: CodecTypes["pg/int4@1"]["output"];
    name: CodecTypes["pg/text@1"]["output"];
    province: CodecTypes["pg/text@1"]["output"];
    region: CodecTypes["pg/text@1"]["output"];
    category: CodecTypes["pg/text@1"]["output"];
    description: CodecTypes["pg/text@1"]["output"];
    image: CodecTypes["pg/text@1"]["output"];
    bestFor: CodecTypes["pg/text@1"]["output"] | null;
    mapsUrl: CodecTypes["pg/text@1"]["output"] | null;
    createdAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
    bookings: public_Booking[];
    reviews: public_Review[];
    readonly [RelationKeys]?: "bookings" | "reviews";
  };
  export type public_Food = {
    id: CodecTypes["pg/int4@1"]["output"];
    name: CodecTypes["pg/text@1"]["output"];
    description: CodecTypes["pg/text@1"]["output"];
    image: CodecTypes["pg/text@1"]["output"];
    category: CodecTypes["pg/text@1"]["output"];
    createdAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
    readonly [RelationKeys]?: never;
  };
  export type public_Tip = {
    id: CodecTypes["pg/int4@1"]["output"];
    title: CodecTypes["pg/text@1"]["output"];
    description: CodecTypes["pg/text@1"]["output"];
    category: CodecTypes["pg/text@1"]["output"];
    image: CodecTypes["pg/text@1"]["output"] | null;
    createdAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
    readonly [RelationKeys]?: never;
  };
  export type public_Booking = {
    id: CodecTypes["pg/int4@1"]["output"];
    userId: CodecTypes["pg/int4@1"]["output"];
    destinationId: CodecTypes["pg/int4@1"]["output"];
    bookingDate: CodecTypes["pg/timestamptz-temporal@1"]["output"];
    status: CodecTypes["pg/text@1"]["output"];
    createdAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
    destination: public_Destination;
    user: public_User;
    readonly [RelationKeys]?: "destination" | "user";
  };
  export type public_Review = {
    id: CodecTypes["pg/int4@1"]["output"];
    userId: CodecTypes["pg/int4@1"]["output"];
    destinationId: CodecTypes["pg/int4@1"]["output"];
    rating: CodecTypes["pg/int4@1"]["output"];
    comment: CodecTypes["pg/text@1"]["output"];
    createdAt: CodecTypes["pg/timestamptz-temporal@1"]["output"];
    destination: public_Destination;
    user: public_User;
    readonly [RelationKeys]?: "destination" | "user";
  };
}

export declare const models: {
  public: {
    User: Models.public_User;
    Destination: Models.public_Destination;
    Food: Models.public_Food;
    Tip: Models.public_Tip;
    Booking: Models.public_Booking;
    Review: Models.public_Review;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: "public";
        readonly kind: "postgres-schema";
        readonly entries: {
          readonly table: {
            readonly booking: {
              columns: {
                readonly id: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "autoincrement()";
                  };
                };
                readonly userId: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                };
                readonly destinationId: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                };
                readonly bookingDate: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-temporal@1";
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "literal";
                    readonly value: DefaultLiteralValue<"pg/text@1", "PENDING">;
                  };
                };
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-temporal@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "now()";
                  };
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: "booking_userId_idx_a489d58a";
                  readonly prefix: "booking_userId_idx";
                  readonly columns: readonly ["userId"];
                  readonly unique: false;
                },
                {
                  readonly name: "booking_destinationId_idx_1646ee5c";
                  readonly prefix: "booking_destinationId_idx";
                  readonly columns: readonly ["destinationId"];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "booking";
                    readonly columns: readonly ["userId"];
                  };
                  readonly target: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "user";
                    readonly columns: readonly ["id"];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "booking";
                    readonly columns: readonly ["destinationId"];
                  };
                  readonly target: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "destination";
                    readonly columns: readonly ["id"];
                  };
                },
              ];
            };
            readonly destination: {
              columns: {
                readonly id: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "autoincrement()";
                  };
                };
                readonly name: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly province: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly region: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly category: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly description: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly image: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly bestFor: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly mapsUrl: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-temporal@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "now()";
                  };
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly food: {
              columns: {
                readonly id: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "autoincrement()";
                  };
                };
                readonly name: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly description: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly image: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly category: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-temporal@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "now()";
                  };
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly review: {
              columns: {
                readonly id: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "autoincrement()";
                  };
                };
                readonly userId: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                };
                readonly destinationId: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                };
                readonly rating: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                };
                readonly comment: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-temporal@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "now()";
                  };
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: "review_userId_idx_a489d58a";
                  readonly prefix: "review_userId_idx";
                  readonly columns: readonly ["userId"];
                  readonly unique: false;
                },
                {
                  readonly name: "review_destinationId_idx_1646ee5c";
                  readonly prefix: "review_destinationId_idx";
                  readonly columns: readonly ["destinationId"];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "review";
                    readonly columns: readonly ["userId"];
                  };
                  readonly target: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "user";
                    readonly columns: readonly ["id"];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "review";
                    readonly columns: readonly ["destinationId"];
                  };
                  readonly target: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "destination";
                    readonly columns: readonly ["id"];
                  };
                },
              ];
            };
            readonly tip: {
              columns: {
                readonly id: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "autoincrement()";
                  };
                };
                readonly title: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly description: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly category: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly image: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-temporal@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "now()";
                  };
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly user: {
              columns: {
                readonly id: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "autoincrement()";
                  };
                };
                readonly name: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly password: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly role: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "literal";
                    readonly value: DefaultLiteralValue<"pg/text@1", "USER">;
                  };
                };
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-temporal@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "now()";
                  };
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [{ readonly columns: readonly ["email"] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  "roots" | "domain"
> & {
  readonly target: "postgres";
  readonly targetFamily: "sql";
  readonly roots: {
    readonly user: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "User";
    };
    readonly destination: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "Destination";
    };
    readonly food: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "Food";
    };
    readonly tip: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "Tip";
    };
    readonly booking: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "Booking";
    };
    readonly review: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "Review";
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Booking: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly destinationId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly bookingDate: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-temporal@1";
                };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-temporal@1";
                };
              };
            };
            readonly relations: {
              readonly destination: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "Destination";
                };
                readonly cardinality: "N:1";
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ["destinationId"];
                  readonly targetFields: readonly ["id"];
                };
              };
              readonly user: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "User";
                };
                readonly cardinality: "N:1";
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ["userId"];
                  readonly targetFields: readonly ["id"];
                };
              };
            };
            readonly storage: {
              readonly table: "booking";
              readonly namespaceId: "public";
              readonly fields: {
                readonly id: { readonly column: "id" };
                readonly userId: { readonly column: "userId" };
                readonly destinationId: { readonly column: "destinationId" };
                readonly bookingDate: { readonly column: "bookingDate" };
                readonly status: { readonly column: "status" };
                readonly createdAt: { readonly column: "createdAt" };
              };
            };
          };
          readonly Destination: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly province: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly region: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly category: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly description: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly image: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly bestFor: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly mapsUrl: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-temporal@1";
                };
              };
            };
            readonly relations: {
              readonly bookings: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "Booking";
                };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["destinationId"];
                };
              };
              readonly reviews: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "Review";
                };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["destinationId"];
                };
              };
            };
            readonly storage: {
              readonly table: "destination";
              readonly namespaceId: "public";
              readonly fields: {
                readonly id: { readonly column: "id" };
                readonly name: { readonly column: "name" };
                readonly province: { readonly column: "province" };
                readonly region: { readonly column: "region" };
                readonly category: { readonly column: "category" };
                readonly description: { readonly column: "description" };
                readonly image: { readonly column: "image" };
                readonly bestFor: { readonly column: "bestFor" };
                readonly mapsUrl: { readonly column: "mapsUrl" };
                readonly createdAt: { readonly column: "createdAt" };
              };
            };
          };
          readonly Food: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly description: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly image: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly category: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-temporal@1";
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: "food";
              readonly namespaceId: "public";
              readonly fields: {
                readonly id: { readonly column: "id" };
                readonly name: { readonly column: "name" };
                readonly description: { readonly column: "description" };
                readonly image: { readonly column: "image" };
                readonly category: { readonly column: "category" };
                readonly createdAt: { readonly column: "createdAt" };
              };
            };
          };
          readonly Review: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly destinationId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly rating: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly comment: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-temporal@1";
                };
              };
            };
            readonly relations: {
              readonly destination: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "Destination";
                };
                readonly cardinality: "N:1";
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ["destinationId"];
                  readonly targetFields: readonly ["id"];
                };
              };
              readonly user: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "User";
                };
                readonly cardinality: "N:1";
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ["userId"];
                  readonly targetFields: readonly ["id"];
                };
              };
            };
            readonly storage: {
              readonly table: "review";
              readonly namespaceId: "public";
              readonly fields: {
                readonly id: { readonly column: "id" };
                readonly userId: { readonly column: "userId" };
                readonly destinationId: { readonly column: "destinationId" };
                readonly rating: { readonly column: "rating" };
                readonly comment: { readonly column: "comment" };
                readonly createdAt: { readonly column: "createdAt" };
              };
            };
          };
          readonly Tip: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly description: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly category: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly image: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-temporal@1";
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: "tip";
              readonly namespaceId: "public";
              readonly fields: {
                readonly id: { readonly column: "id" };
                readonly title: { readonly column: "title" };
                readonly description: { readonly column: "description" };
                readonly category: { readonly column: "category" };
                readonly image: { readonly column: "image" };
                readonly createdAt: { readonly column: "createdAt" };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly password: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly role: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-temporal@1";
                };
              };
            };
            readonly relations: {
              readonly bookings: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "Booking";
                };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["userId"];
                };
              };
              readonly reviews: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "Review";
                };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["userId"];
                };
              };
            };
            readonly storage: {
              readonly table: "user";
              readonly namespaceId: "public";
              readonly fields: {
                readonly id: { readonly column: "id" };
                readonly name: { readonly column: "name" };
                readonly email: { readonly column: "email" };
                readonly password: { readonly column: "password" };
                readonly role: { readonly column: "role" };
                readonly createdAt: { readonly column: "createdAt" };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract["storage"]["namespaces"];
